### ISSUE TITLE
vs2017编译时,tokenTokenDecode出错

### ISSUE THREAD

**Issue by LukeLIN-web** [IshiKura-a/CPP_PROJECT_2020#11]
tokenTokenDecode.dll出错 ,显示
1.在什么环境/情况下遇到了什么问题。
2020 .7.17 clone  branch master,

平台: vs2017

tokendecode.lib
tokendecoded.lib
显示无法解析的外部命令
![image](https://user-images.githubusercontent.com/60426396/87782758-b14bac00-c865-11ea-9b25-8c1c54a7c176.png)

**Comment by uninstalle** [comment]
使用vs2019生成的静态库似乎无法在vs2017中使用，
最新的commit中已经转用tokendecode的动态库，
请验证是否能正常通过编译
